[google]
credentials = """
{
  "installed": {
    "client_id": "your-client-id.apps.googleusercontent.com",
    "project_id": "your-project-id",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "151132433020-fu2t6tgo1hgpgjndpj1d6rv1jt0rhp6u.apps.googleusercontent.com",
    "redirect_uris": ["http://localhost"]
  }
}
"""
